---
output: html_document
editor_options: 
  chunk_output_type: console
---
# Impact of German Sampling Protocol on Condition Modelling

```{r, message=F, include=F}
direct <- "Y:/Offshore scallop/Assessment/"
mwger <- read.csv(paste0(direct, "Data/Survey_data/2018/Spring/Ger/mw_Data.csv"))
mwger_0 <- read.csv(paste0(direct, "Data/Survey_data/2018/Spring/Ger/mw_Data_inclCommercial.csv"))

shfger <- read.csv(paste0(direct, "Data/Survey_data/2018/Spring/Ger/Survey1985-2018.csv"))
shfger_0 <- read.csv(paste0(direct, "Data/Survey_data/2018/Spring/Ger/Survey1985-2018_inclCommercial.csv"))

load("C:/Documents/Offshore scallop/Assessment/Data/Survey_data/2018/Survey_summary_output/testing_results_GermanSurveyOnly.RData")
HtWt.fit <- cf.data$Ger$HtWt.fit

load("C:/Documents/Offshore scallop/Assessment/Data/Survey_data/2018/Survey_summary_output/testing_results_GermanInclCommercial.RData")
HtWt.fit_0 <- cf.data$Ger$HtWt.fit

direct = "C:/Documents/Offshore scallop/Assessment/"

require(ggplot2)
require(plyr)
require(dplyr)
require(reshape2)
require(pander)
require(lme4)
require(grid)
require(gridExtra)
require(sp)
require(rgdal)
require(maptools)
require(raster)
require(rgeos)
require(fields)

```

```{r, include=F, warning=F, message=F}
### create multiple versions of the CF-TS figure with different subsets of data
### this requires models with different data subsets
testplot <- function(mwdat, shfger) {
  source("C:/Documents/Offshore scallop/Assessment/Assessment_fns/Survey_and_OSAC/shwt.lme.r")
  source("C:/Documents/Offshore scallop/Assessment/Assessment_fns/Survey_and_OSAC/condFac.R")
  source("C:/Documents/Offshore scallop/Assessment/Assessment_fns/Survey_and_OSAC/shwt.plt1.R")
  source("C:/Documents/Offshore scallop/Assessment/Assessment_fns/Survey_and_OSAC/stdts.plt.R")

  mwdat$ID <- as.character(mwdat$ID)
  condmod <- condFac(na.omit(mwdat),shfger,model.type='gam_f',dirct=direct)
  
  mwdat$sh <- mwdat$sh/100

  mwshmod <- shwt.lme(mwdat, random.effect='ID', b.par=3, verbose = T)
    condmod$CFyrs <- join(condmod$CFyrs, data.frame(year=1985:2018), type="right")
    
  cf.lab <-expression(paste("CF:",bgroup("(",frac(g,dm^3)   ,")")))
  
  # par(mfrow=c(1,2))
  # shwt.plt1(mwshmod,lw=3,ht=10,wd=12,cx=1.5,cex.mn = 2,las=1, titl = "MW-SH Relationship (Ger-2018)", axis.cx = 1, yl=c(0,90), xl=c(.60,1.90))
  # stdts.plt(condmod$CFyrs,y=c('CF'),pch=c(23),col=c('blue'),ylab=cf.lab,
  #           mean.line=T,graphic='none',xlab='Year',ylim=c(4,25),las=1,
  #           titl = "Condition factor time series (Ger)",cex.mn=2,tx.ypos=4, error=T)

  list(mwshmod=mwshmod, condmod=condmod)

}

data="mwger_0"
full <- testplot(mwger_0, shfger_0)
old <- testplot(mwger_0[mwger_0$year<2008,], shfger_0)
new <- testplot(mwger_0[mwger_0$year>2007,], shfger_0)
big <- testplot(mwger_0[mwger_0$sh>89,], shfger_0)
big_new <- testplot(mwger_0[mwger_0$sh>89 & mwger_0$year>2009,], shfger_0)
```

### Change in MWSH relationship
```{r, message=F, warning=F, echo=F}
MWSH_temp <- rbind(
      data.frame(old$mwshmod$data, pred=old$mwshmod$data$sh^old$mwshmod$B * old$mwshmod$A, run="old"), 
      data.frame(new$mwshmod$data, pred=new$mwshmod$data$sh^new$mwshmod$B * new$mwshmod$A, run="new"))

MWSH_size <- rbind(
      data.frame(big$mwshmod$data, pred=big$mwshmod$data$sh^big$mwshmod$B * big$mwshmod$A, run="big"),
      data.frame(big_new$mwshmod$data, pred=big_new$mwshmod$data$sh^big_new$mwshmod$B * big_new$mwshmod$A, run="big_new"),
      data.frame(old$mwshmod$data, pred=old$mwshmod$data$sh^old$mwshmod$B * old$mwshmod$A, run="old"), 
      data.frame(new$mwshmod$data, pred=new$mwshmod$data$sh^new$mwshmod$B * new$mwshmod$A, run="new"))

png(paste0(direct, "/2019/Presentations/Special_industry_presentations/MWSH shift_temp_", data, ".png"), height=6, width=6, units="in", res=490)
ggplot() + geom_line(data=MWSH_temp, aes(sh*100, pred, colour=run, linetype=run)) +
  theme_bw() + theme(panel.grid=element_blank())+
  ylab("Meat Weight (g)") +
  xlab("Shell Height (mm)") +
  scale_colour_manual(name="Time series", labels=c("\nBefore 2008\n(unlined gear)\n", "2008+\n(lined gear)"), values=c("blue", "red")) +
  scale_linetype_discrete(name="Time series", labels=c("\nBefore 2008\n(unlined gear)\n", "2008+\n(lined gear)")) +
  scale_x_continuous(limits=c(55,200), breaks = seq(60, 200, 20), expand = c(0.01,0)) +
  scale_y_continuous(breaks = seq(0, 80, 10), expand=expand_scale(mult=c(0.05,0.1)))
dev.off() 

png(paste0(direct, "/2019/Presentations/Special_industry_presentations/MWSH shift_size_", data, ".png"), height=6, width=6, units="in", res=490)
ggplot() + geom_line(data=MWSH_size[MWSH_size$run %in% c("big", "big_new"),], aes(sh*100, pred, colour=run, linetype=run)) +
  theme_bw() + theme(panel.grid=element_blank())+
   ylab("Meat Weight (g)") +
  xlab("Shell Height (mm)") +
  scale_colour_manual(name="Data group", labels=c("\n>89, all years\n", ">89, 2008+"), values=c("black", "blue")) +
  scale_linetype_discrete(name="Data group", labels=c("\n>89, all years\n", ">89, 2008+"))
dev.off()

png(paste0(direct, "/2019/Presentations/Special_industry_presentations/MWSH shift_size_temp_", data, ".png"), height=6, width=6, units="in", res=490)
ggplot() + geom_line(data=MWSH_size[!MWSH_size$run %in% c("big_new"),], aes(sh*100, pred, colour=run, linetype=run)) +
  theme_bw() + theme(panel.grid=element_blank())+
   ylab("Meat Weight (g)") +
  xlab("Shell Height (mm)") +
  scale_colour_manual(name="Data group", labels=c("\n>89mm, all years\n", "\nBefore 2008\n(unlined gear)\n", "2008+\n(lined gear)\n"), values=c("black", "blue", "red")) +
  scale_linetype_discrete(name="Data group", labels=c("\n>89mm, all years\n", "\nBefore 2008\n(unlined gear)\n", "2008+\n(lined gear)\n"))
dev.off()

```

### Change in condition model estimate error through time
```{r, message=F,warning=F,  echo=F}
CFyrs_temp <- rbind(#data.frame(full$condmod$CFyrs, run="full"), 
      data.frame(old$condmod$CFyrs, run="old"), 
      data.frame(new$condmod$CFyrs, run="new")#, 
      #data.frame(big$condmod$CFyrs, run="big"), 
      #data.frame(big_new$condmod$CFyrs, run="big_new")
      )

CFyrs_size <- rbind(#data.frame(full$condmod$CFyrs, run="full"), 
      #data.frame(old$condmod$CFyrs, run="old"), 
      #data.frame(new$condmod$CFyrs, run="new")#, 
      data.frame(big$condmod$CFyrs, run="big"), 
      data.frame(big_new$condmod$CFyrs, run="big_new"))

png(paste0(direct, "/2019/Presentations/Special_industry_presentations/Precision ts_", data, ".png"), height=6, width=8.5, units="in", res=490)
ggplot() + geom_point(data=CFyrs_temp, aes(year, CFse.fit, colour=run, shape=run)) +
  geom_line(data=CFyrs_temp, aes(year, CFse.fit, colour=run)) +
  theme_bw() + theme(panel.grid = element_blank())+
  geom_smooth(data=CFyrs_temp, aes(year, CFse.fit), method="lm", colour="black", lty="dashed", se=F) +
  ylab("Estimate uncertainty") +
  xlab("Year") +
  scale_colour_manual(name="Time series", labels=c("\nBefore 2008\n(unlined gear)\n", "2008+\n(lined gear)"), values=c("blue", "red"))+
  scale_shape_discrete(name="Time series", labels=c("\nBefore 2008\n(unlined gear)\n", "2008+\n(lined gear)"))
dev.off()
```

### What if we pretend that we kept using unlined gear? 
```{r, echo=F, message=F, warning=F, fig.width=15, fig.height=8}
png(paste0(direct, "/2019/Presentations/Special_industry_presentations/MWSH_above89mm_", data, ".png"), width = 13,height = 8.75,res=420, units="in")
cf.lab <-expression(paste("CF:",bgroup("(",frac(g,dm^3)   ,")")))
par(mfrow=c(1,2))
shwt.plt1(big$mwshmod,lw=3,ht=10,wd=12,cx=1.5,cex.mn = 2,las=1, titl = "MW-SH Relationship\n(Standardized, >89mm)", axis.cx = 1, yl=c(0,90), xl=c(.60,1.90))
stdts.plt(big$condmod$CFyrs,y=c('CF'),pch=c(23),col=c('black'),ylab=cf.lab,
          mean.line=T,graphic='none',xlab='Year',ylim=c(4,25),las=1,
          titl = "Condition factor time series\n(Standardized, >89mm)",cex.mn=2,tx.ypos=4, error=T)
dev.off()
```

### Statistical test of before and after 2008
```{r}
big$condmod$CFyrs$time[big$condmod$CFyrs$year <2008] <- "before"
big$condmod$CFyrs$time[big$condmod$CFyrs$year >2007] <- "after"

summary(lm(data=big$condmod$CFyrs, CF ~ time, weights = 1/CFse.fit))
summary(lm(data=big$condmod$CFyrs, CF ~ time))

full$condmod$CFyrs$time[big$condmod$CFyrs$year <2008] <- "before"
full$condmod$CFyrs$time[big$condmod$CFyrs$year >2007] <- "after"


summary(lm(data=full$condmod$CFyrs, CF ~ time, weights = 1/CFse.fit))
summary(lm(data=full$condmod$CFyrs, CF ~ time))

```

### comparing lined and unlined SHF unsampled and sampled tows
```{r}
head(mwger_0)

mwger_0$gear[mwger_0$year<2008] <- "unlined"
mwger_0$gear[mwger_0$year>2007] <- "lined"
shfger_0$gear[shfger_0$year<2008] <- "unlined"
shfger_0$gear[shfger_0$year>2007] <- "lined"

png(paste0(direct, "/2019/Presentations/Special_industry_presentations/SHF_gear_detailed_mwger_0.png"), width = 13,height = 8.75,res=420, units="in")
ggplot() + geom_histogram(data=mwger_0, aes(sh), binwidth=5) + facet_wrap(~gear, nrow=2) +
  theme_bw() + 
  theme(panel.grid=element_blank()) +
  scale_x_continuous(breaks=seq(0,200, 10))
dev.off()

shfger_0_melt <- melt(shfger_0, id.vars=c("ID","year","gear", "cruise", "bank", "tow", "lon", "lat"), measure.vars = dput(paste0("h", seq(5,200,5))))

shfger_0_melt$sh <- as.numeric(gsub(x=shfger_0_melt$variable, "h", ""))

png(paste0(direct, "/2019/Presentations/Special_industry_presentations/SHF_gear_general_shfger_0.png"), width = 13,height = 8.75,res=420, units="in")
ggplot() + geom_histogram(data=shfger_0_melt, aes(sh, value), stat="identity", binwidth=5) + facet_wrap(~gear, nrow=2) +
  theme_bw() + 
  theme(panel.grid=element_blank())+
  scale_x_continuous(breaks=seq(0,200, 10))
dev.off()

```

