---
title: "Untitled"
output: word_document
---

```{r, echo=F, include=F}

require(readxl)
require(tidyverse)
require(pander)

direct.proj <- "Y:/Projects/CSAS/2y_Projection_RAP/"

cs.GBa.s0 <- read_xlsx(paste0(direct.proj,"data/GBa/decisiontables.xlsx"),sheet="2021_Surplus0")
cs.GBa.sm <- read_xlsx(paste0(direct.proj,"data/GBa/decisiontables.xlsx"),sheet="2021_SurplusMedian")
cs.GBa.sp <- read_xlsx(paste0(direct.proj,"data/GBa/decisiontables.xlsx"),sheet="2021_SurplusPrevious")
cs.BBn.s0 <- read_xlsx(paste0(direct.proj,"data/BBn/decisiontables.xlsx"),sheet="2021_Surplus0")
cs.BBn.sm <- read_xlsx(paste0(direct.proj,"data/BBn/decisiontables.xlsx"),sheet="2021_SurplusMedian")
cs.BBn.sp <- read_xlsx(paste0(direct.proj,"data/BBn/decisiontables.xlsx"),sheet="2021_SurplusPrevious")

head.name <- c("**Catch (t)**",
               "**Exploitation\nRate**", 
               "**Probability of\nBiomass\nDecline**",
               "**Expected\nChange in\nBiomass (%)**",  
               "**Probability\nbiomass will\nexceed LRP**", 
               "**Probability\nbiomass will\nexceed USR**")

# GB 3 cases first surplus 0 scenario
tab.GBa.s0 <- cs.GBa.s0 %>% dplyr::select(adj.catch, mu, pB0, B.change,p.LRP, p.USR) %>% 
                     dplyr::filter(mu >= 0.05 & mu <= 0.25) 
tab.GBa.s0$adj.catch <- round(tab.GBa.s0$adj.catch,digits =-2)
tab.GBa.s0$mu <- round(tab.GBa.s0$mu,digits =2)
tab.GBa.s0$pB0 <- round(tab.GBa.s0$pB0,digits =2)
tab.GBa.s0$B.change <- round(tab.GBa.s0$B.change,digits =1)
tab.GBa.s0$p.LRP<- round(tab.GBa.s0$p.LRP,digits =2)
tab.GBa.s0$p.LRP[tab.GBa.s0$p.LRP == 1] <- "> 0.99"
tab.GBa.s0$p.USR<- round(tab.GBa.s0$p.USR,digits =2)
tab.GBa.s0$p.USR[tab.GBa.s0$p.USR == 1] <- "> 0.99"
names(tab.GBa.s0) <- head.name
row.names(tab.GBa.s0) <- NULL
tab.GBa.s0 <- pander(tab.GBa.s0, split.tables=Inf)

# Next the Median scenario
tab.GBa.sm <- cs.GBa.sm %>% dplyr::select(adj.catch, mu, pB0, B.change, p.LRP ,p.USR) %>% 
                     dplyr::filter(mu >= 0.05 & mu <= 0.25) 
tab.GBa.sm$adj.catch <- round(tab.GBa.sm$adj.catch,digits =-2)
tab.GBa.sm$mu <- round(tab.GBa.sm$mu,digits =2)
tab.GBa.sm$pB0 <- round(tab.GBa.sm$pB0,digits =2)
tab.GBa.sm$B.change <- round(tab.GBa.sm$B.change,digits =1)
tab.GBa.sm$p.LRP<- round(tab.GBa.sm$p.LRP,digits =2)
tab.GBa.sm$p.LRP[tab.GBa.sm$p.LRP == 1] <- "> 0.99"
tab.GBa.sm$p.USR<- round(tab.GBa.sm$p.USR,digits =2)
tab.GBa.sm$p.USR[tab.GBa.sm$p.USR == 1] <- "> 0.99"
names(tab.GBa.sm) <- head.name
row.names(tab.GBa.sm) <- NULL
tab.GBa.sm <- pander(tab.GBa.sm, split.tables=Inf)

#finally the previous year scenario
tab.GBa.sp <- cs.GBa.sp %>% dplyr::select(adj.catch, mu, pB0, B.change, p.LRP ,p.USR) %>% 
                     dplyr::filter(mu >= 0.05 & mu <= 0.25) 
tab.GBa.sp$adj.catch <- round(tab.GBa.sp$adj.catch,digits =-2)
tab.GBa.sp$mu <- round(tab.GBa.sp$mu,digits =2)
tab.GBa.sp$pB0 <- round(tab.GBa.sp$pB0,digits =2)
tab.GBa.sp$B.change <- round(tab.GBa.sp$B.change,digits =1)
tab.GBa.sp$p.LRP<- round(tab.GBa.sp$p.LRP,digits =2)
tab.GBa.sp$p.LRP[tab.GBa.sp$p.LRP == 1] <- "> 0.99"
tab.GBa.sp$p.USR<- round(tab.GBa.sp$p.USR,digits =2)
tab.GBa.sp$p.USR[tab.GBa.sp$p.USR == 1] <- "> 0.99"
names(tab.GBa.sp) <- head.name
row.names(tab.GBa.sp) <- NULL
tab.GBa.sp <- pander(tab.GBa.sp, split.tables=Inf)

# Now the 3 BBn cases
# first surplus 0 scenario
tab.BBn.s0 <- cs.BBn.s0 %>% dplyr::select(adj.catch, mu, pB0, B.change) %>% 
                     dplyr::filter(mu >= 0.08 & mu <= 0.25) 
tab.BBn.s0$adj.catch <- round(tab.BBn.s0$adj.catch,digits =-1)
tab.BBn.s0$mu <- round(tab.BBn.s0$mu,digits =2)
tab.BBn.s0$pB0 <- round(tab.BBn.s0$pB0,digits =2)
tab.BBn.s0$B.change <- round(tab.BBn.s0$B.change,digits =1)
#tab.BBn.s0$p.LRP<- round(tab.BBn.s0$p.LRP,digits =2)
#tab.BBn.s0$p.USR<- round(tab.BBn.s0$p.USR,digits =2)
names(tab.BBn.s0) <- head.name[1:4]
row.names(tab.BBn.s0) <- NULL
tab.BBn.s0 <- pander(tab.BBn.s0, split.tables=Inf)

# Next the Median scenario
tab.BBn.sm <- cs.BBn.sm %>% dplyr::select(adj.catch, mu, pB0, B.change) %>% 
                     dplyr::filter(mu >= 0.08 & mu <= 0.25) 
tab.BBn.sm$adj.catch <- round(tab.BBn.sm$adj.catch,digits =-1)
tab.BBn.sm$mu <- round(tab.BBn.sm$mu,digits =2)
tab.BBn.sm$pB0 <- round(tab.BBn.sm$pB0,digits =2)
tab.BBn.sm$B.change <- round(tab.BBn.sm$B.change,digits =1)
#tab.BBn.sm$p.LRP<- round(tab.BBn.sm$p.LRP,digits =2)
#tab.BBn.sm$p.USR<- round(tab.BBn.sm$p.USR,digits =2)
names(tab.BBn.sm) <- head.name[1:4]
row.names(tab.BBn.sm) <- NULL
tab.BBn.sm <- pander(tab.BBn.sm, split.tables=Inf)

#finally the previous year scenario
tab.BBn.sp <- cs.BBn.sp %>% dplyr::select(adj.catch, mu, pB0, B.change) %>% 
                     dplyr::filter(mu >= 0.08 & mu <= 0.25) 
tab.BBn.sp$adj.catch <- round(tab.BBn.sp$adj.catch,digits =-1)
tab.BBn.sp$mu <- round(tab.BBn.sp$mu,digits =2)
tab.BBn.sp$pB0 <- round(tab.BBn.sp$pB0,digits =2)
tab.BBn.sp$B.change <- round(tab.BBn.sp$B.change,digits =1)
#tab.BBn.sp$p.LRP<- round(tab.BBn.sp$p.LRP,digits =2)
#tab.BBn.sp$p.USR<- round(tab.BBn.sp$p.USR,digits =2)
names(tab.BBn.sp) <- head.name[1:4]
row.names(tab.BBn.sp) <- NULL
tab.BBn.sp <- pander(tab.BBn.sp, split.tables=Inf)

```

```{r, echo=F}
tab.GBa.s0
```

```{r, echo=F}
tab.GBa.sm
```

```{r, echo=F}
tab.GBa.sp
```

```{r, echo=F}
tab.BBn.s0
```

```{r, echo=F}
tab.BBn.sm
```

```{r, echo=F}
tab.BBn.sp
```

